### PR TITLE
Add in the ability to color the region outline.

### PR DESCRIPTION
**Pull request by Josharias**
Having been recently up and down a bunch of shaders,  I knew that adding in a color to this would be easy.  And it was!

### CODE REVIEW

**Comment by Josharias** [comment]
Oh,  forgot the screenshot.  Attained by changing my prefab to (at least for the green one):

```
  "RegionOutline": {
    "color": [0,255,0,0]
  },
```

terasology-160503160347-1280x720

**Comment by Cervator** [comment]
Yessss.... distinct workshop rooms :D

**Comment by Cervator** [comment]
Merged with the main PR - exists in upstream develop now :-)

**Comment by flo** [comment]
Cool

**Pull request closed without merging**
